[font]
normal = { family= "CaskaydiaCove Nerd Font", style="Regular" }
size = 12.0


[window]
opacity = 0.9
blur = true
resize_increments = true
padding = { x = 2, y = 2 }
dimensions = { columns= 120, lines = 50}
